INST 354 - 0201
Final Project

Penelope Newcomb

In [12]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_auc_score, roc_curve, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn import preprocessing
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
shark_df = pd.read_csv("C:\\Users\\pnewc\\Desktop\\INST 354\\IOTC_ll_untuned_final_predict.csv")

In [14]:
shark_filtered = shark_df[['year', 'latitude', 'longitude', 'species_sciname', 'pres_abs','zone']]

from sklearn.preprocessing import LabelEncoder
shark_filtered = shark_filtered.apply(LabelEncoder().fit_transform)

shark_filtered.head()

year  latitude  longitude  species_sciname  pres_abs  zone
0     0         3          0                6         1   135
1     0         3          0                5         1   135
2     0         3          0                4         1   135
3     0         3          0                7         1   135
4     0         3          0                2         0   135

In [15]:
x = shark_filtered.drop("pres_abs", axis=1)
y = shark_filtered['pres_abs'] 

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [17]:
LogReg = LogisticRegression()
LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

In [18]:
print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

Classes [0 1]
Intercept [-1.27700239]
Coefficients [[-0.03665034  0.06451016 -0.08762735  0.24718132 -0.00163682]]


In [19]:
print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

Accuracy 0.7013333333333334
              precision    recall  f1-score   support

           0       0.74      0.90      0.81      2447
           1       0.40      0.17      0.24       928

    accuracy                           0.70      3375
   macro avg       0.57      0.54      0.53      3375
weighted avg       0.65      0.70      0.66      3375



In [20]:
conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

array([[2210,  237],
       [ 771,  157]], dtype=int64)

In [21]:
#ALOPIAS
alopias = shark_filtered[shark_filtered["species_sciname"]==0]
x = alopias.drop("pres_abs",axis=1)
y = alopias.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-3.70760548]
Coefficients [[ 0.19902951  1.0730789  -0.71096524  0.         -0.08463487]]
Accuracy 0.9626666666666667
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       361
           1       0.00      0.00      0.00        14

    accuracy                           0.96       375
   macro avg       0.48      0.50      0.49       375
weighted avg       0.93      0.96      0.94       375



c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

array([[361,   0],
       [ 14,   0]], dtype=int64)

In [22]:
#CARCHARHINIDAE
carch = shark_filtered[shark_filtered["species_sciname"]==1]
x = carch.drop("pres_abs",axis=1)
y = carch.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-6.60209395]
Coefficients [[-0.07803284 -0.01435962 -1.35454109  0.         -1.65909816]]
Accuracy 0.9973333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       374
           1       0.00      0.00      0.00         1

    accuracy                           1.00       375
   macro avg       0.50      0.50      0.50       375
weighted avg       0.99      1.00      1.00       375



c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

array([[374,   0],
       [  1,   0]], dtype=int64)

In [23]:
#CARCHARHINUS FALCIFORMIS
falci = shark_filtered[shark_filtered["species_sciname"]==2]
x = falci.drop("pres_abs",axis=1)
y = falci.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-0.53606435]
Coefficients [[ 0.13759815  1.19397344 -1.00858162  0.         -0.23063648]]
Accuracy 0.744
              precision    recall  f1-score   support

           0       0.75      0.82      0.79       215
           1       0.73      0.64      0.68       160

    accuracy                           0.74       375
   macro avg       0.74      0.73      0.73       375
weighted avg       0.74      0.74      0.74       375



array([[177,  38],
       [ 58, 102]], dtype=int64)

In [24]:
#CARCHARHINUS LONGIMANUS
longi = shark_filtered[shark_filtered["species_sciname"]==3]
x = longi.drop("pres_abs",axis=1)
y = longi.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-3.08640634]
Coefficients [[-0.33578631  0.54178318 -0.10668458  0.          0.01786762]]
Accuracy 0.9493333333333334
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       356
           1       0.00      0.00      0.00        19

    accuracy                           0.95       375
   macro avg       0.47      0.50      0.49       375
weighted avg       0.90      0.95      0.92       375



c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

array([[356,   0],
       [ 19,   0]], dtype=int64)

In [25]:
#LAMNA NASUS
lamna = shark_filtered[shark_filtered["species_sciname"]==4]
x = lamna.drop("pres_abs",axis=1)
y = lamna.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-2.81866571]
Coefficients [[-0.61493204 -0.29138989 -0.62343828  0.         -0.27861428]]
Accuracy 0.936
              precision    recall  f1-score   support

           0       0.94      1.00      0.97       351
           1       0.00      0.00      0.00        24

    accuracy                           0.94       375
   macro avg       0.47      0.50      0.48       375
weighted avg       0.88      0.94      0.91       375



c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

array([[351,   0],
       [ 24,   0]], dtype=int64)

In [26]:
#LAMNIDAE
lamni = shark_filtered[shark_filtered["species_sciname"]==5]
x = lamni.drop("pres_abs",axis=1)
y = lamni.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [1.15862339]
Coefficients [[-0.01110158 -0.27389563 -0.83100451  0.         -0.15892363]]
Accuracy 0.8053333333333333
              precision    recall  f1-score   support

           0       0.93      0.27      0.42        97
           1       0.80      0.99      0.88       278

    accuracy                           0.81       375
   macro avg       0.86      0.63      0.65       375
weighted avg       0.83      0.81      0.76       375



array([[ 26,  71],
       [  2, 276]], dtype=int64)

In [27]:
#PRIONACE GLAUCA
prion = shark_filtered[shark_filtered["species_sciname"]==6]
x = prion.drop("pres_abs",axis=1)
y = prion.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [1.88899632]
Coefficients [[-0.31107978 -0.42983795 -0.8927983   0.         -0.17801102]]
Accuracy 0.8613333333333333
              precision    recall  f1-score   support

           0       1.00      0.12      0.21        59
           1       0.86      1.00      0.92       316

    accuracy                           0.86       375
   macro avg       0.93      0.56      0.57       375
weighted avg       0.88      0.86      0.81       375



array([[  7,  52],
       [  0, 316]], dtype=int64)

In [28]:
#SHARKS NEI
nei = shark_filtered[shark_filtered["species_sciname"]==7]
x = nei.drop("pres_abs",axis=1)
y = nei.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-0.35779957]
Coefficients [[-0.76744848  0.81296026 -1.09823753  0.         -0.22405417]]
Accuracy 0.7306666666666667
              precision    recall  f1-score   support

           0       0.73      0.76      0.74       192
           1       0.73      0.70      0.72       183

    accuracy                           0.73       375
   macro avg       0.73      0.73      0.73       375
weighted avg       0.73      0.73      0.73       375



array([[145,  47],
       [ 54, 129]], dtype=int64)

In [29]:
#SPHYRNA
sphyrna = shark_filtered[shark_filtered["species_sciname"]==8]
x = sphyrna.drop("pres_abs",axis=1)
y = sphyrna.pres_abs
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
LogReg = LogisticRegression()

scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

LogReg.fit(x_train,y_train)

y_pred=LogReg.predict(x_test)

print('Classes', LogReg.classes_)
print('Intercept',LogReg.intercept_)
print("Coefficients", LogReg.coef_ )

print("Accuracy", LogReg.score(x_test, y_test))
print(classification_report(y_test, LogReg.predict(x_test)))

conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

Classes [0 1]
Intercept [-3.7999059]
Coefficients [[ 0.04013368  1.04553627 -0.78023348  0.         -0.14486138]]
Accuracy 0.968
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       363
           1       0.00      0.00      0.00        12

    accuracy                           0.97       375
   macro avg       0.48      0.50      0.49       375
weighted avg       0.94      0.97      0.95       375



c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\pnewc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

array([[363,   0],
       [ 12,   0]], dtype=int64)